# If you press Ctrl-a twice, it sends the actual Ctrl-a to the shell 
# (essential for jumping to the start of a line in Bash/Zsh)
bind C-a send-prefix

# Source .tmux.conf as suggested in `man tmux`
bind R source-file ~/.config/tmux/tmux.conf

# Make it easier to create new window
bind C-c new-window

# Allow killing session
bind X confirm-before -p "Kill tmux session? (y/n)" kill-session

# Intuitive splits
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

# navigate panes with Alt + hjkl (No prefix required)
# 2026-02 try this for a while and if I get used to it remove the bindings with prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Navigate panes using hjkl, and ctrl+hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

# swap panes
bind J swap-pane -D
bind K swap-pane -U
bind H join-pane -t :-
bind L join-pane -t :+

# allow repeating commands in window navigation
bind -r n next-window
bind -r p previous-window

# move window left and right, allowing repeats
bind -r P swap-window -t -1\; select-window -t -1
bind -r N swap-window -t +1\; select-window -t +1

# renumber windows if one is deleted
set-option -g renumber-windows on

bind A command-prompt -I "#W" "rename-window '%%'"

setw -g status-keys emacs

# Enable wm window titles, simple session:window
set -g set-titles on
set -g set-titles-string '#S : #W'

# Copy-paste
bind -T copy-mode-vi v send-keys -X begin-selection
if-shell "uname | grep -q Darwin" \
    'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"'
if-shell "uname | grep -q Linux" \
    'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clip"'

set -g status-position top       # Move status bar to top
